# 배포 후 확인
# spec.template.spec.nodeSelector에 맞게 노드에 레이블 부여 후 확인
# 해당 부분 주석 처리 -> 재배포 -> 확인
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myapp-ds
spec:
  selector:
    matchLabels:
      app: myapp-ds
  template:
    metadata:
      labels:
        app: myapp-ds
    spec:
      nodeSelector:
        node: development
      containers:
        - name: myapp
          image: ghcr.io/nobreak-labs/go-myweb:alpine
          ports:
            - containerPort: 8080
