apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myapp-sts
spec:
  selector:
    matchLabels:
      app: myapp-sts
  serviceName: myapp-svc-headless
  replilcas: 2
  template:
    metadata:
      labels:
        app: myapp-sts
    spec:
      containers:
        - name: myapp
          image: ghcr.io/nobreak-labs/go-myweb:alpine
          ports:
            - containerPort: 8080
