# livenessProbe 진단 결과가 실패여서 30초마다 파드가 재시작됨
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-liveness-404.yml
spec:
  containers:
    - name: myapp
      image: ghcr.io/nobreak-labs/go-myweb:alpine
      ports:
        - containerPort: 8080
          protocol: TCP
      livenessProbe:
        httpHet:
          path: /health?code=404
          port: 8080
