# startupProbe 진단 실패여서 파드가 Ready 상태로 변하지 않는다.
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-startup
spec:
  containers:
    - name: myapp
      image: ghcr.io/nobreak-labs/go-myweb:alpine
      ports:
        - containerPort: 8080
          protocol: TCP
      startupProbe:
        httpGet:
          path: /health?code=404
          port: 8080
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
