# 클라이언트 IP가 같다면 같은 파드로 연결되도록 유지한다.
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc-ses-aff
spec:
  sessionAffinity: ClientIP
  type: ClusterIP
  selector:
    app: myapp-rs
  ports:
    - port: 80
      targetPort: 8080
