# controller/myapp-rs-readiness.yml와 함께 배포
# 레디니스 프로브 동작 확인
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc-readiness
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: myapp-rs-readiness
