# 레플리카셋의 파드 템플릿 컨테이너 포트에 이름을 부여해서
# 그 이름을 서비스 포트에 지정
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs-namedport
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-rs-namedport
  template:
    metadata:
      labels:
        app: myapp-rs-namedport
    spec:
      containers:
        - name: myapp
          image: ghcr.io/nobreak-labs/go-myweb:alpine
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-svc-namedport
spec:
  ports:
    - name: http
      port: 80
      targetPort: http # 포트 이름으로 지정
  selector:
    app: myapp-rs-namedport
