apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs-np
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-rs-np
  template:
    metadata:
      labels:
        app: myapp-rs-np
    spec:
      containers:
        - name: myapp
          image: ghcr.io/nobreak-labs/go-myweb:alpine
          ports:
            - containerPort: 8080
